### ISSUE TITLE
Windows 10 Build 10586.79 is out

### ISSUE THREAD

**Issue by EphraimB** [Studio384/ChangeWindows#10]
Please update changewindows.org to show that the latest stable version of windows is 10586.79

**Comment by Studio384** [comment]
On what platform? On both Phone and Desktop, the latest build is 10586.71 and we don't really cover other editions beyond that (like Xbox, IoT, etc.).

**Comment by EphraimB** [comment]
http://winaero.com/blog/microsoft-bumps-windows-10-version-to-10586-79-with-kb3136562-update/

**Comment by Studio384** [comment]
This update hasn't been released.

**Comment by EphraimB** [comment]
Then why does this article on winaero.com say it does?

**Comment by Studio384** [comment]
Because they found the update on Microsofts servers. But as long as Microsoft doesn't release that update, it isn't released. It would be the same thing if we would claim that Windows 8.1 version 6.2.9600.17013 was released in February instead of April 8th. Because it leaks, doesn't make it released.
